services:
    mysql:
        image: mysql:8
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: riftdex
            MYSQL_USER: riftdex
            MYSQL_PASSWORD: riftdex
            MYSQL_ROOT_PASSWORD: riftdex
        ports:
            - '3306:3306'
        volumes:
            - riftdex-mysql:/var/lib/mysql

volumes:
    riftdex-mysql:
